### ISSUE TITLE
Clear minified css on rocket clean

### ISSUE THREAD

**Issue by MaximeCulea** [GeekPress/wp-rocket-cli#32] opened 2020-11-13 09:14 UTC
Hi there 👋 

It seems that the minified css app/cache/min/1/302db68e96b941e4f4ffd635934b23df.css is not cleared or regenerated by no one command.
I had to go in the dashboard and hit "clean cache" and it worked.

**Comment by GeekPress** [comment] 2020-12-01 13:53
Closing it as it's a duplicate of #25

**Closed as completed by GeekPress** 2020-12-01 13:53 UTC
Labels: duplicate
